name: continuous-integration

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: ESLint
        run: npm run lint

      - name: Prettier
        run: npm run format:ci

      - name: TSC
        run: npm run type:ci
